# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anya.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nanya.proto\x12\x04\x61nya\"\x19\n\x07\x43onvReq\x12\x0e\n\x06in_str\x18\x01 \x01(\t\"*\n\x07\x43onvRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07out_str\x18\x02 \x01(\t\"\x1d\n\x0bPartConvReq\x12\x0e\n\x06in_str\x18\x01 \x01(\t\".\n\x0bPartConvRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07out_str\x18\x02 \x03(\t2m\n\x06\x41nyaIM\x12)\n\x07\x43onvert\x12\r.anya.ConvReq\x1a\r.anya.ConvRsp\"\x00\x12\x38\n\x0ePartialConvert\x12\x11.anya.PartConvReq\x1a\x11.anya.PartConvRsp\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anya_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONVREQ._serialized_start=20
  _CONVREQ._serialized_end=45
  _CONVRSP._serialized_start=47
  _CONVRSP._serialized_end=89
  _PARTCONVREQ._serialized_start=91
  _PARTCONVREQ._serialized_end=120
  _PARTCONVRSP._serialized_start=122
  _PARTCONVRSP._serialized_end=168
  _ANYAIM._serialized_start=170
  _ANYAIM._serialized_end=279
# @@protoc_insertion_point(module_scope)
